title: Revapi 
org: Lukas Krejci
base_url: '${project.distributionManagement.site.url}'
scm: 'https://github.com/revapi/revapi'
version: '${project.version}'

asciidoctor:
  :safe: safe
  :attributes:
    base_url: '${project.distributionManagement.site.url}'
    docs_url: 'docs'
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
    source-highlighter: coderay
    coderay-css: style
    scm: '${project.scm.url}'
    version: '${project.version}'

profiles:
  development:
    base_url: "http://localhost:4242"
    asciidoctor:
      :attributes:
         base_url: "http://localhost:4242"
  production:
    base_url: "${project.distributionManagement.site.url}"
    google_analytics: UA-57095904-1
    asciidoctor:
      :attributes:
         base_url: "${project.distributionManagement.site.url}"
    deploy:
      host: github_pages
      branch: master

