language: java
jdk:
  - oraclejdk8

notifications:
  email: false

sudo: false

#force travis to use a newer version of Java8.
addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ffc2f0f6f86121dd38e2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

