language: java
jdk:
  - oraclejdk8

notifications:
  email: false

sudo: false

#force travis to use a newer version of Java8.
addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2
