# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn verify --batch-mode --fail-at-end
      - run:
          command: |
            for test in `find -name 'TEST-*.xml'`; do
              test_name=${test//+(*\/|.xml)}
              mkdir -p /tmp/test-results/$test_name
              cp $test /tmp/test-results/$test_name/results.xml
            done
          when: always
      - store_test_results:
          path: /tmp/test-results
      # upload the coverage report to codecov
      - run: bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -X xcode
  java9:
    docker:
      - image: circleci/openjdk:9-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn verify --batch-mode --fail-at-end
      - run:
          command: |
            for test in `find -name 'TEST-*.xml'`; do
              test_name=${test//+(*\/|.xml)}
              mkdir -p /tmp/test-results/$test_name
              cp $test /tmp/test-results/$test_name/results.xml
            done
          when: always
      - store_test_results:
          path: /tmp/test-results
  java10:
    docker:
      - image: circleci/openjdk:10-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn verify --batch-mode --fail-at-end
      - run:
          command: |
            for test in `find -name 'TEST-*.xml'`; do
              test_name=${test//+(*\/|.xml)}
              mkdir -p /tmp/test-results/$test_name
              cp $test /tmp/test-results/$test_name/results.xml
            done
          when: always
      - store_test_results:
          path: /tmp/test-results
workflows:
  version: 2
  build:
    jobs:
      - java8
      - java9
      - java10

